version: "3.8"
services:

  configserver:
    image: rezacomplete/configserver
    mem_limit: 700m
    ports:
      - "8083:8083"
    networks:
      - users

  user:
    image: rezacomplete/user
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - users
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 45s
        max_attempts: 3
        window: 360s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8083/
#  education:
#    image: rezacomplete/education
#    mem_limit: 700m
#    ports:
#      - "8082:8082"
#    networks:
#      - users
#    depends_on:
#      - configserver
#    deploy:
#      restart_policy:
#        condition: on-failure
#        delay: 5s
#        max_attempts: 3
#        window: 120s
#    environment:
#      SPRING_PROFILES_ACTIVE: default
#      SPRING_CONFIG_IMPORT: configserver:http://configserver:8083/


#  post:
#    image: rezacomplete/post
#    mem_limit: 700m
#    ports:
#      - "8081:8081"
#    networks:
#      - users
#    depends_on:
#      - configserver
#    deploy:
#      restart_policy:
#        condition: on-failure
#        delay: 5s
#        max_attempts: 3
#        window: 120s
#    environment:
#      SPRING_PROFILES_ACTIVE: default
#      SPRING_CONFIG_IMPORT: configserver:http://configserver:8083/

networks:
  users: