apiVersion: v1
kind: Service
metadata:
  name: user

spec:
  selector:
    app: user
  ports:
    - name: tcp
      port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: education

spec:
  selector:
    app: education
  ports:
    - name: tcp
      port: 8082
      targetPort: 8082
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: post

spec:
  selector:
    app: post
  ports:
    - name: tcp
      port: 8081
      targetPort: 8081
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: zipkin
spec:
  selector:
    app: zipkin
  type: ClusterIP
  ports:
    - name: tcp
      port: 9411
      targetPort: 9411

---
apiVersion: v1
kind: Service
metadata:
  name: gatewayserver

spec:
  selector:
    app: gatewayserver
  ports:
    - name: tcp
      port: 8084
      targetPort: 8084
  type: LoadBalancer
