apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
spec:
  selector:
    matchLabels:
      app: user
  replicas: 1
  template: #template for the pods
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: rezacomplete/user
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: default