apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
spec:
  selector:
    matchLabels:
      app: user
  replicas: 1
  template: #template for the pods
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: rezacomplete/user
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: SPRING_CONFIG_IMPORT
              value: configserver:http://configserver:8083
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: education
spec:
  selector:
    matchLabels:
      app: education
  replicas: 1
  template: #template for the pods
    metadata:
      labels:
        app: education
    spec:
      containers:
        - name: education
          image: rezacomplete/education
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: post
spec:
  selector:
    matchLabels:
      app: post
  replicas: 1
  template: #template for the pods
    metadata:
      labels:
        app: post
    spec:
      containers:
        - name: post
          image: rezacomplete/post
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: default
