apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
spec:
  selector:
    matchLabels:
      app: user
  replicas: 1
  template: #template for the pods
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: rezacomplete/user
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: SPRING_PROFILES_ACTIVE
            - name: SPRING_ZIPKIN_BASEURL
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: SPRING_ZIPKIN_BASEURL
            - name: URL_POST
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: URL_POST
            - name: URL_EDUCATION
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: URL_EDUCATION
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: education
spec:
  selector:
    matchLabels:
      app: education
  replicas: 1
  template: #template for the pods
    metadata:
      labels:
        app: education
    spec:
      containers:
        - name: education
          image: rezacomplete/education
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: SPRING_PROFILES_ACTIVE
            - name: SPRING_ZIPKIN_BASEURL
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: SPRING_ZIPKIN_BASEURL

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: post
spec:
  selector:
    matchLabels:
      app: post
  replicas: 1
  template: #template for the pods
    metadata:
      labels:
        app: post
    spec:
      containers:
        - name: post
          image: rezacomplete/post
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: SPRING_PROFILES_ACTIVE
            - name: SPRING_ZIPKIN_BASEURL
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: SPRING_ZIPKIN_BASEURL

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipkin
  labels:
    app: zipkin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zipkin
  template:
    metadata:
      labels:
        app: zipkin
    spec:
      containers:
        - name: zipkin
          image: openzipkin/zipkin
          ports:
            - containerPort: 9411

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gatewayserver
  labels:
    app: gatewayserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gatewayserver
  template:
    metadata:
      labels:
        app: gatewayserver
    spec:
      containers:
        - name: gatewayserver
          image: rezacomplete/gatewayserver
          ports:
            - containerPort: 8084
